### ISSUE TITLE
Error with NuVotifier and Luckperms

### ISSUE THREAD

**Issue by andrewkm** [parallelblock/NuVotifier#101]
Made two tickets previously but got convinced it might be something on my end so closed them.
Now after extensive testing, I'm definitely positive there's some sort of confliction happening with NuVotifier and Luckperms:

Error: https://pastebin.com/raw/aUT2gmQd

**Comment by andrewkm** [comment]
@ichbinjoe
Worth mentioning:
https://github.com/lucko/LuckPerms/issues/1153
https://github.com/lucko/LuckPerms/issues/1212

**Comment by Ichbinjoe** [comment]
So I talked with @astei about this some, and I think we came to the conclusion that we will be getting rid of slf4j. Obviously that's the cop-out solution, but when it comes down to it slf4j can't be relocated easily.

**Comment by Ichbinjoe** [comment]
This should be fixed here: https://repo.parallelblock.com/repository/public-raw/nuvotifier/nuvotifier.jar

**Comment by andrewkm** [comment]
Confirmed fixed. @Ichbinjoe
