### ISSUE TITLE
Error on console 

### ISSUE THREAD

**Issue by comonier** [parallelblock/NuVotifier#105]
Error on console 
https://hastebin.com/henunijuzu.apache

i have already erase old key deleted old dfile, deleted plugin folder, he always create the same old publick key and i think so it s not working... he did not accept that public key and do not give me a new one, is ever and ever the same one.

**Comment by comonier** [comment]
16.10 23:40:36 [Server] ERROR [Votifier] Unable to process vote from /192.99.101.31:56916
16.10 23:40:36 [Server] INFO com.vexsoftware.votifier.netty.handler.codec.CorruptedFrameException: Could not decrypt data (is your key correct?)
16.10 23:40:36 [Server] INFO at com.vexsoftware.votifier.net.protocol.VotifierProtocol1Decoder.decode(VotifierProtocol1Decoder.java:34) ~[nuvotifier-2.4.0.jar:?]
16.10 23:40:36 [Server] INFO at com.vexsoftware.votifier.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489) ~[nuvotifier-2.4.0.jar:?]
16.10 23:40:36 [Server] INFO at com.vexsoftware.votifier.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428) ~[nuvotifier-2.4.0.jar:?]
16.10 23:40:36 [Server] INFO at com.vexsoftware.votifier.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) ~[nuvotifier-2.4.0.jar:?]
16.10 23:40:36 [Server] INFO at com.vexsoftware.votifier.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [nuvotifier-2.4.0.jar:?]
16.10 23:40:36 [Server] INFO at com.vexsoftware.votifier.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [nuvotifier-2.4.0.jar:?]
16.10 23:40:36 [Server] INFO at com.vexsoftware.votifier.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [nuvotifier-2.4.0.jar:?]
16.10 23:40:36 [Server] INFO at com.vexsoftware.votifier.netty.handler.codec.ByteToMessageDecoder.handlerRemoved(ByteToMessageDecoder.java:236) [nuvotifier-2.4.0.jar:?]
16.10 23:40:36 [Server] INFO at com.vexsoftware.votifier.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:494) [nuvotifier-2.4.0.jar:?]
16.10 23:40:36 [Server] INFO at com.vexsoftware.votifier.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428) [nuvotifier-2.4.0.jar:?]
16.10 23:40:36 [Server] INFO at com.vexsoftware.votifier.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) [nuvotifier-2.4.0.jar:?]
16.10 23:40:36 [Server] INFO at com.vexsoftware.votifier.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [nuvotifier-2.4.0.jar:?]
16.10 23:40:36 [Server] INFO at com.vexsoftware.votifier.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [nuvotifier-2.4.0.jar:?]
16.10 23:40:36 [Server] INFO at com.vexsoftware.votifier.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [nuvotifier-2.4.0.jar:?]
16.10 23:40:36 [Server] INFO at com.vexsoftware.votifier.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) [nuvotifier-2.4.0.jar:?]
16.10 23:40:36 [Server] INFO at com.vexsoftware.votifier.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [nuvotifier-2.4.0.jar:?]
16.10 23:40:36 [Server] INFO at com.vexsoftware.votifier.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [nuvotifier-2.4.0.jar:?]
16.10 23:40:36 [Server] INFO at com.vexsoftware.votifier.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [nuvotifier-2.4.0.jar:?]
16.10 23:40:36 [Server] INFO at com.vexsoftware.votifier.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359) [nuvotifier-2.4.0.jar:?]
16.10 23:40:36 [Server] INFO at com.vexsoftware.votifier.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [nuvotifier-2.4.0.jar:?]
16.10 23:40:36 [Server] INFO at com.vexsoftware.votifier.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [nuvotifier-2.4.0.jar:?]
16.10 23:40:36 [Server] INFO at com.vexsoftware.votifier.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935) [nuvotifier-2.4.0.jar:?]
16.10 23:40:36 [Server] INFO at com.vexsoftware.votifier.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134) [nuvotifier-2.4.0.jar:?]
16.10 23:40:36 [Server] INFO at com.vexsoftware.votifier.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645) [nuvotifier-2.4.0.jar:?]
16.10 23:40:36 [Server] INFO at com.vexsoftware.votifier.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580) [nuvotifier-2.4.0.jar:?]
16.10 23:40:36 [Server] INFO at com.vexsoftware.votifier.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497) [nuvotifier-2.4.0.jar:?]
16.10 23:40:36 [Server] INFO at com.vexsoftware.votifier.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459) [nuvotifier-2.4.0.jar:?]
16.10 23:40:36 [Server] INFO at com.vexsoftware.votifier.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [nuvotifier-2.4.0.jar:?]
16.10 23:40:36 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
16.10 23:40:36 [Server] INFO Caused by: javax.crypto.BadPaddingException: Decryption error
16.10 23:40:36 [Server] INFO at sun.security.rsa.RSAPadding.unpadV15(Unknown Source) ~[?:1.8.0_131]
16.10 23:40:36 [Server] INFO at sun.security.rsa.RSAPadding.unpad(Unknown Source) ~[?:1.8.0_131]
16.10 23:40:36 [Server] INFO at com.sun.crypto.provider.RSACipher.doFinal(RSACipher.java:363) ~[sunjce_provider.jar:1.8.0_112]
16.10 23:40:36 [Server] INFO at com.sun.crypto.provider.RSACipher.engineDoFinal(RSACipher.java:389) ~[sunjce_provider.jar:1.8.0_112]
16.10 23:40:36 [Server] INFO at javax.crypto.Cipher.doFinal(Cipher.java:2165) ~[?:1.8.0_121]
16.10 23:40:36 [Server] INFO at com.vexsoftware.votifier.net.protocol.v1crypto.RSA.decrypt(RSA.java:58) ~[?:?]
16.10 23:40:36 [Server] INFO at com.vexsoftware.votifier.net.protocol.VotifierProtocol1Decoder.decode(VotifierProtocol1Decoder.java:32) ~[?:?]
16.10 23:40:36 [Server] INFO ... 28 more

**Comment by Ichbinjoe** [comment]
Definitely a problem with the keypair... if you delete the folder (plugins/Votifier on Bukkit) it _will_ generate a new public key. It always does. This is validated behavior. Closing, reopen if you have more evidence to suggest that there is a software anomaly.

**Comment by comonier** [comment]
https://hastebin.com/apodedegaf.css

step 1) i turned server off
step 2) i deleted Votifier Folder (plugins/Votifier on Bukkit)
step 3) i turned server on

console log:
https://hastebin.com/apodedegaf.css

issue still
