### ISSUE TITLE
i did erase folder, plugin, everthing with server down, but still creating same public key.

### ISSUE THREAD

**Issue by comonier** [parallelblock/NuVotifier#106]
step 1) i turned server off
step 2) i deleted Votifier Folder (plugins/Votifier on Bukkit)
step 3) i turned server on

console log:
https://hastebin.com/apodedegaf.css

issue still

edit: i cant re-open old tickets already closed by you
https://github.com/parallelblock/NuVotifier/issues/105

**Comment by comonier** [comment]
ok it really generated a new key - my bad - it think was the same cause
start and end with same caracters but problem still ?

**Comment by Ichbinjoe** [comment]
Wait. Are you using the token in the log or public.key?

**Comment by comonier** [comment]
works finally you was right - my bad
