### ISSUE TITLE
NuVotifier could not set up PluginMessaging for vote forwarding!

### ISSUE THREAD

**Issue by andrewkm** [parallelblock/NuVotifier#107]
Getting this on a new server I've just finished setting up.
No idea why, I've set up the plugin exactly the same way across all servers. Thoughts?

https://pastebin.com/raw/r8ZzKvaG

**Comment by Ichbinjoe** [comment]
Spigot 1.13 requires the : to appear in the pluginMessaging channel. You are using a 1.13 server. You _must_ change the pluginMessaging channel. The new default is `nuvotifier:votes`

**Comment by andrewkm** [comment]
@Ichbinjoe changed my config to:

`# The IP to listen to. Use 0.0.0.0 if you wish to listen to all interfaces on your server. (All IP addresses)
# This defaults to the IP you have configured your server to listen on, or 0.0.0.0 if you have not configured this.
host: 0.0.0.0

# Port to listen for new votes on
port: -1

# Whether or not to print debug messages. In a production system, this should be set to false.
# This is useful when initially setting up NuVotifier to ensure votes are being delivered.
debug: false

# Setting this option to true will disable handling of Protocol v1 packets. While the old protocol is not secure, this
# option is currently not recommended as most voting sites only support the old protocol at present. However, if you are
# using NuVotifier's proxy forwarding mechanism, enabling this option will increase your server's security.
disable-v1-protocol: false

# All tokens, labeled by the serviceName of each server list.
tokens:
  # Default token for all server lists, if another isn't supplied.
  default: 1db8u7qh1vcqgsqfgt902e1uov

# Configuration section for all vote forwarding to NuVotifier
forwarding:
  # Sets whether to set up a remote method for fowarding. Supported methods:
  # - none - Does not set up a forwarding method.
  # - pluginMessaging - Sets up plugin messaging
  method: nuvotifier:votes
  pluginMessaging:
    channel: NuVotifier`

Getting this:
https://pastebin.com/raw/dz8yRZ0z

**Comment by Ichbinjoe** [comment]
Please review the default configuration https://github.com/parallelblock/NuVotifier/blob/master/bukkit/src/main/resources/bukkitConfig.yml

Your method should still be pluginMessaging and the channel should be changed to nuvotifier:votes.

**Comment by andrewkm** [comment]
Thanks @Ichbinjoe this fixed the issue for me.
