### ISSUE TITLE
[1.13.2] Unable to process vote

### ISSUE THREAD

**Issue by Quavelen** [parallelblock/NuVotifier#108]
Spigot just updated to 1.13.2, and it seems to have borked NuVotifer. Is there a possibility you could add support for it?

https://www.spigotmc.org/threads/bukkit-craftbukkit-spigot-bungeecord-1-13-2.344189

The only error it gives, is when a vote is made. It simply states "Unable to process vote", like this:
`[Mon, 22. Oct 2018 15:18:30 MDT ERROR] [Votifier] Unable to process vote from /<redacted IP>`

**Comment by Ichbinjoe** [comment]
Turn on debug. Unless bungee / spigot changed something very drastic, this is not related to version.

**Comment by Quavelen** [comment]
> Turn on debug. Unless bungee / spigot changed something very drastic, this is not related to version.

Yeah, I was wrong. That error was from a player who has a dynamic IP, and hadn't yet logged into the server with that IP.
