### ISSUE TITLE
Vote comes in, error inside NuVotifierBukkit at line 365

### ISSUE THREAD

**Issue by ProSl3nderMan** [parallelblock/NuVotifier#111]
Good afternoon,
This is my first time using NuVotifier, so I am unsure if this broke in 1.13.2 or 1.13.1. My server is on 1.13.2 right now. What I do know is I get this error when I received a vote:
https://pastebin.com/JBFyihhn
I get this error if the player has never joined, has joined but is not online, and player is online.
Server vote site is minecraft-server-list.com.

Let me know if I need to provide any other information,
Austin

**Comment by Ichbinjoe** [comment]
Restart your server. Do not use /reload or Plugman. This has never been supported. NuVotifier works fine for 1.13.2 as well as all Bukkit versions.

**Comment by ProSl3nderMan** [comment]
My apologies, I used /plugman load so I didn't have to restart with people on. Will restart the server.

Thank you!
