### ISSUE TITLE
Legal vote was blocked after an error

### ISSUE THREAD

**Issue by TheoRetisch1** [parallelblock/NuVotifier#118]
Hej, a player voted for our server on the server list  server.eu. The vote was registered in the log of the server list. On our server the vote was blocked with the following error: https://pastebin.com/JSqAAaWN 
Votes shortly before and after arrived without problems. From the site minecraft-serverlist.net all votes went through at the same time.
Can you do anything about it or is there a problem with the serverlist?
I appreciate any help you can provide :)

NuVotifier: 2.4.1
Paper 1.12.2 #1594
Windows Server 2012 R2

**Comment by Ichbinjoe** [comment]
While this likely won't help you much at all, NuVotifier is now at 2.5.0.

As for your actual error, it looks like `An existing connection was software controlled
canceled by the host computer` (english translation of your error message) is a decently common error where the remote site (in your case sls.eu) closes its connection before the vote processing completes. Could you try the latest dev build (https://repo.parallelblock.com/repository/public-raw/nuvotifier/nuvotifier.jar) and see if that helps at all?

**Comment by TheoRetisch1** [comment]
Thanks for the dev version on which page can I find the dev build?
The problem is that the error is very rare. But I'll keep watching it after the update and close the ticket if it doesn't happen for a while. Thanks for the help!

**Comment by Ichbinjoe** [comment]
I gave you a link to the dev build above. Simply use that jar.

Unfortunately this is a random bug which has a lot to do with your server as well as the remote server list's procedure for sending a vote. If you encounter it again, simply comment on this issue again and I'll look into it more.

**Comment by TheoRetisch1** [comment]
It happened again. My setup hasn't changed except for the dev-version that I've been using for 13 days now. The error rarely occurs, but it does occur and causes complaints xD. The error occurs only together with the page minecraft-server.eu, the page serverlist.net works fine. Do you still have ideas?

error: https://pastebin.com/RxyYytuG

**Comment by TheoRetisch1** [comment]
The bug still occurs very rarely.
Any ideas?

Error: https://pastebin.com/hifXcjY7
Paper 1.13.2 #624
Votifier: 2.5.2
SuperbVote 0.5.4
