### ISSUE TITLE
bungeecord vote

### ISSUE THREAD

**Issue by justinbea** [parallelblock/NuVotifier#57]
setting up an vote system for bungee to for now skyblock server

config bungee: https://pastebin.com/K0u63Ci7
config skyblock: https://pastebin.com/LFCvjTrX
i think error in console: https://pastebin.com/UrvKFCAs

**Comment by Ichbinjoe** [comment]
What error?

**Comment by justinbea** [comment]
i dont see any error, when i try to do an test for votifier they cant connect

**Comment by Ichbinjoe** [comment]
I find it bizzare you specified a IPv4 address for your configurations but bound to an IPv6 address. Try specifying 0.0.0.0 as your host.

**Comment by Ichbinjoe** [comment]
After looking at your logs, this is a 'first startup' log, leaving you with a chicken-egg problem of the configurations you provided - please provide a fresh log.
