### ISSUE TITLE
UNABLE TO SEND VOTE !!!

### ISSUE THREAD

**Issue by LoLMeCZ** [parallelblock/NuVotifier#69]
> 13:38:45 [SEVERE] [NuVotifier] Unable to send vote to /185.91.116.21:8192. This
> vote will be lost!
> com.vexsoftware.votifier.netty.handler.codec.CorruptedFrameException: Handshake
> is not valid.
> at com.vexsoftware.votifier.bungee.forwarding.proxy.client.VotifierProtocol2
> HandshakeHandler.channelRead0(VotifierProtocol2HandshakeHandler.java:24)
> at com.vexsoftware.votifier.bungee.forwarding.proxy.client.VotifierProtocol2
> HandshakeHandler.channelRead0(VotifierProtocol2HandshakeHandler.java:9)
> at com.vexsoftware.votifier.netty.channel.SimpleChannelInboundHandler.channe
> lRead(SimpleChannelInboundHandler.java:105)
> at com.vexsoftware.votifier.netty.channel.AbstractChannelHandlerContext.invo
> keChannelRead(AbstractChannelHandlerContext.java:362)
> at com.vexsoftware.votifier.netty.channel.AbstractChannelHandlerContext.invo
> keChannelRead(AbstractChannelHandlerContext.java:348)
> at com.vexsoftware.votifier.netty.channel.AbstractChannelHandlerContext.fire
> ChannelRead(AbstractChannelHandlerContext.java:340)
> at com.vexsoftware.votifier.netty.handler.codec.MessageToMessageDecoder.chan
> nelRead(MessageToMessageDecoder.java:102)
> at com.vexsoftware.votifier.netty.channel.AbstractChannelHandlerContext.invo
> keChannelRead(AbstractChannelHandlerContext.java:362)
> at com.vexsoftware.votifier.netty.channel.AbstractChannelHandlerContext.invo
> keChannelRead(AbstractChannelHandlerContext.java:348)
> at com.vexsoftware.votifier.netty.channel.AbstractChannelHandlerContext.fire
> ChannelRead(AbstractChannelHandlerContext.java:340)
> at com.vexsoftware.votifier.netty.handler.timeout.IdleStateHandler.channelRe
> ad(IdleStateHandler.java:286)
> at com.vexsoftware.votifier.netty.channel.AbstractChannelHandlerContext.invo
> keChannelRead(AbstractChannelHandlerContext.java:362)
> at com.vexsoftware.votifier.netty.channel.AbstractChannelHandlerContext.invo
> keChannelRead(AbstractChannelHandlerContext.java:348)
> at com.vexsoftware.votifier.netty.channel.AbstractChannelHandlerContext.fire
> ChannelRead(AbstractChannelHandlerContext.java:340)
> at com.vexsoftware.votifier.netty.handler.codec.ByteToMessageDecoder.fireCha
> nnelRead(ByteToMessageDecoder.java:310)
> at com.vexsoftware.votifier.netty.handler.codec.ByteToMessageDecoder.channel
> Read(ByteToMessageDecoder.java:284)
> at com.vexsoftware.votifier.netty.channel.AbstractChannelHandlerContext.invo
> keChannelRead(AbstractChannelHandlerContext.java:362)
> at com.vexsoftware.votifier.netty.channel.AbstractChannelHandlerContext.invo
> keChannelRead(AbstractChannelHandlerContext.java:348)
> at com.vexsoftware.votifier.netty.channel.AbstractChannelHandlerContext.fire
> ChannelRead(AbstractChannelHandlerContext.java:340)
> at com.vexsoftware.votifier.netty.channel.DefaultChannelPipeline$HeadContext
> .channelRead(DefaultChannelPipeline.java:1359)
> at com.vexsoftware.votifier.netty.channel.AbstractChannelHandlerContext.invo
> keChannelRead(AbstractChannelHandlerContext.java:362)
> at com.vexsoftware.votifier.netty.channel.AbstractChannelHandlerContext.invo
> keChannelRead(AbstractChannelHandlerContext.java:348)
> at com.vexsoftware.votifier.netty.channel.DefaultChannelPipeline.fireChannel
> Read(DefaultChannelPipeline.java:935)
> at com.vexsoftware.votifier.netty.channel.nio.AbstractNioByteChannel$NioByte
> Unsafe.read(AbstractNioByteChannel.java:134)
> at com.vexsoftware.votifier.netty.channel.nio.NioEventLoop.processSelectedKe
> y(NioEventLoop.java:645)
> at com.vexsoftware.votifier.netty.channel.nio.NioEventLoop.processSelectedKe
> ysOptimized(NioEventLoop.java:580)
> at com.vexsoftware.votifier.netty.channel.nio.NioEventLoop.processSelectedKe
> ys(NioEventLoop.java:497)
> at com.vexsoftware.votifier.netty.channel.nio.NioEventLoop.run(NioEventLoop.
> java:459)
> at com.vexsoftware.votifier.netty.util.concurrent.SingleThreadEventExecutor$
> 5.run(SingleThreadEventExecutor.java:858)
> at com.vexsoftware.votifier.netty.util.concurrent.DefaultThreadFactory$Defau
> ltRunnableDecorator.run(DefaultThreadFactory.java:138)
> at java.lang.Thread.run(Thread.java:748)

PLEASE HELP ME :///

**Comment by LoLMeCZ** [comment]
Hey,
Really please help :/
I want to use this plugin really !

**Comment by chuckatlampros** [comment]
Welcome to GitHub!

This is an open source project, the maintainers have day jobs.  The maintainers offer the software for free, and make a good faith effort to support a wide range of server configurations.

The best way to get help on an open source project is to provide as detailed description of your environment along with the error you are recieving, politely.

**Comment by Ichbinjoe** [comment]
@LoLMeCZ Ensure your backend is the correct IP and port, and that it is online. This is a configuration issue.

**Comment by LoLMeCZ** [comment]
I´ve settuped a new port but but still sending new error Unable to send vote to....
Please help me :(

**Comment by LoLMeCZ** [comment]
Please can you make a Skype with me ? :P
I don´t know what happens but every NuVotifier on Bungee still worked now no ?
Please...

**Comment by Ichbinjoe** [comment]
I do not provide free support. I can continue providing support through this issue.
