### ISSUE TITLE
NuVotifier receives a vote Successfully, but errors out

### ISSUE THREAD

**Issue by Ryuhouji** [parallelblock/NuVotifier#70]
Hi. I'm a dev for an FTB Revelation server on 1.12.2(revelation 1.5.0)
Currently we're experiencing issues with NuVotifer not registerring votes to the listener. Here's a pastebin link for the error message we get, IP's Redacted for privacy and security concerns.
https://pastebin.com/x6bGHFZ1
I'm sure that NuVotifier is set up properly, and updated.

**Comment by Ichbinjoe** [comment]
https://github.com/parallelblock/NuVotifier/releases

You are not updated. Latest version is 2.3.6 which fixes this problem.
