### ISSUE TITLE
Some votes not comming through

### ISSUE THREAD

**Issue by x1p** [parallelblock/NuVotifier#72]
07.03 10:40:55 [Server] SEVERE Unable to process vote from /185.56.63.151:39592 07.03 10:40:55 [Server] INFO java.io.IOException: Connection reset by peer 07.03 10:40:55 [Server] INFO at sun.nio.ch.FileDispatcherImpl.read0(Native Method) 07.03 10:40:55 [Server] INFO at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) 07.03 10:40:55 [Server] INFO at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) 07.03 10:40:55 [Server] INFO at sun.nio.ch.IOUtil.read(IOUtil.java:192) 07.03 10:40:55 [Server] INFO at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) 07.03 10:40:55 [Server] INFO at com.vexsoftware.votifier.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288) 07.03 10:40:55 [Server] INFO at com.vexsoftware.votifier.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1106) 07.03 10:40:55 [Server] INFO at com.vexsoftware.votifier.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:343) 07.03 10:40:55 [Server] INFO at com.vexsoftware.votifier.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123) 07.03 10:40:55 [Server] INFO at com.vexsoftware.votifier.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645) 07.03 10:40:55 [Server] INFO at com.vexsoftware.votifier.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580) 07.03 10:40:55 [Server] INFO at com.vexsoftware.votifier.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497) 07.03 10:40:55 [Server] INFO at com.vexsoftware.votifier.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459) 07.03 10:40:55 [Server] INFO at com.vexsoftware.votifier.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) 07.03 10:40:55 [Server] INFO at com.vexsoftware.votifier.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138) 07.03 10:40:55 [Server] INFO at java.lang.Thread.run(Thread.java:748)

**Comment by Ichbinjoe** [comment]
#27
