### ISSUE TITLE
Votes aren't reaching server

### ISSUE THREAD

**Issue by Luysita** [parallelblock/NuVotifier#74]
Hello,

I am setting up Votifier, read up the guides and such but for some reason the votes aren't reaching the server "Vanilla", only Bungeecord.

It does this everytime I send a test vote: https://pastebin.com/Q1jyaNxa
But when I actually tested with my character it didn't do anything.

Configs:
https://pastebin.com/TK42uShQ
https://pastebin.com/qBfCj9yK

Really appreciate any help!
Thank you!

**Comment by Ichbinjoe** [comment]
When a test vote works, it means that the backbone that NuVotifier provides is functioning correctly. I find it odd that a test vote would work yet a real vote would not. Were you testing with a test vote on the same site that you were sending the real vote through as? Double check the IP which the site is targeting.
