### ISSUE TITLE
Proxy forwarding for ports > ~32k rolls over resulting in an invalid port

### ISSUE THREAD

**Issue by Armek15** [parallelblock/NuVotifier#76]
Error log:
https://pastebin.com/5tg1LMsw

My **config.yml** setup
https://pastebin.com/Mfb16r0B

**Comment by Ichbinjoe** [comment]
Wow this is embarrasing. I'll get this fixed up tonight and release a new version. Thanks for reporting this!

**Comment by Ichbinjoe** [comment]
You can pull the latest NuVotifier jar from here: https://repo.parallelblock.com/repository/public-raw/nuvotifier/nuvotifier.jar

Its built from the current HEAD commit from the repository.

**Comment by Armek15** [comment]
Thanks!

**Comment by R1NZLER15** [comment]
Uhm, im still having issues, the votes aren't being logged

**Comment by Ichbinjoe** [comment]
Open a new issue with new logs and configurations of both the proxy and backend servers.
