### ISSUE TITLE
Votes are not reaching the backend server

### ISSUE THREAD

**Issue by R1NZLER15** [parallelblock/NuVotifier#77]
2 days ago i submitted the issue: https://github.com/parallelblock/NuVotifier/issues/76

It got fixed in a few hours, but when i finished setting up the Votifier and registered my server on a voting site i noticed that the votes weren't reaching my server, there was not even an error log.

Proxy setup:
IP: 158.69.249.152
**config.yml**: https://pastebin.com/Mfb16r0B

Backend setup:
**config.yml**: https://pastebin.com/PeirtM3k

(proxy) public key: 
`MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArTKMp/FOl0vCiZXwWmSRCA1ybGmRVp+m11+BOGjEnEy8VQ0lzIv+lUrm0o/1UExeQsAuoti5mjxZNOPbIrgmqKJknjViQqulK+4i1cvvilT0tUB4mGzSzNu0CqIZm5WrUTFdtZ9tzJk3godFE1WPBVWMsShRZcxedZH/0pni8iTBGF9pSyQ/F3ZWjpWx0yC0OoGey2OFLTsZ/qNSy10zsTRgZ/pMz0yIe631ogDEY2kLHKJFm5LDbZPL01S3g3fW/IffL6jlJr5jRQduMQ0/B2eA7IkYvfoPQbVJB+EP7IPwFWTq2t54cVPtTGIONJO9v9XSBd0GkiLzDhStv0inWwIDAQAB`
[I will remove the key in a few days]

**Comment by R1NZLER15** [comment]
Oh, the debug mode...
Ok im turning it on.
![image](https://user-images.githubusercontent.com/27157220/38066709-77bd2676-32c6-11e8-8fd0-12968f73c258.png)

**Comment by R1NZLER15** [comment]
hmmmm...
I turned on the debug mode on both proxy and spigot servers, sent some test votes and nothing appeared in the console log.

**Comment by Ichbinjoe** [comment]
Feel free to join our discord for support support. I am closing this issue as it appears to be configuration related.
