### ISSUE TITLE
Offline votes forwarding

### ISSUE THREAD

**Issue by AmazedMender16** [parallelblock/NuVotifier#83]
[NuVotifier] Successfully evicted 8 votes to player 'AmazedMender16.

Thats what shows up in the console. Its adding a ' infront everyones name and the votes never get passed thru to the server the user is on!

EDIT: Offline votes are also case sensitive.

**Comment by AmazedMender16** [comment]
Any update on this issue?

**Comment by Ichbinjoe** [comment]
The logging message is not related to a vote-not-forwarding situation. Logging message has been fixed in b494e1d

**Comment by AmazedMender16** [comment]
What could cause it not to forward offline votes then?
I would be able to troubleshoot if you could let me know

**Comment by Ichbinjoe** [comment]
Please leave detailed reproduction steps - what names you used, services you used, logs, lots of stuff would help.

Offline votes are case sensitive by design. Is there a reason they should not be?

**Comment by Ichbinjoe** [comment]
Please try with latest and reopen if its still happening.
