### ISSUE TITLE
Votetop being empty on some servers

### ISSUE THREAD

**Issue by AmazedMender16** [parallelblock/NuVotifier#86]
Im running the same database for all servers, One of the servers are showing the entire database. the other one is showing 20% of it and the other one is showing nothing... its completely empty.

Am i doing something wrong here? or is this some kind of weird bug

**Comment by Ichbinjoe** [comment]
Not this plugin. Our plugin doesn’t handle vote top.

**Comment by AmazedMender16** [comment]
My bad hahah!
