### ISSUE TITLE
What do I do once it receives votes?

### ISSUE THREAD

**Issue by bobdabiulder** [parallelblock/NuVotifier#87]
Shouldn't there be functionality to give players rewards?  EssentialsX economy tie-in?

**Comment by astei** [comment]
You need to install a listener. This is the plugin that actually gives rewards. Popular ones include GAListener, SuperbVote, and VotingPlugin.

(I am the primary author of SuperbVote.)

**Comment by bobdabiulder** [comment]
Thanks for the reply.  I am confused, I have NuVotifier installed.  When I vote on a website, I get debug output from NV saying it received a vote.  This plugin doesn't seem to have rewards or commands at all.  It just seems to listen.  Do you have it backwards, or am I missing something?

**Comment by md678685** [comment]
@bobdabiulder NuVotifier receives votes and passes them along to a *vote listener* plugin such as the ones @astei mentioned, and those plugins are responsible for giving rewards to players.

`Vote -> <website> -> NuVotifier -> <vote listener> -> <reward>`

**Comment by bobdabiulder** [comment]
Thanks!  I got it now.
