### ISSUE TITLE
Maven Repository Down

### ISSUE THREAD

**Issue by Wowserman** [parallelblock/NuVotifier#91]
Both https://dl.bintray.com/nuvotifier/maven and https://repo.parallelblock.com/repository/maven-public/ seem to be down.

**Comment by MedicOP** [comment]
both are up

**Comment by Ichbinjoe** [comment]
bintray is no longer managed by me (never was, pretty sure tux did that).

sorry about the parallelblock outage, sometimes stuff is stupid.
