### ISSUE TITLE
Cannot connect with 1.13

### ISSUE THREAD

**Issue by Kirrasio** [parallelblock/NuVotifier#95]
We have a 1.12 server on the system as well, before I continue.
It is not allowing the vote to be forwarded, this is the error I'm having in console.
https://pastebin.com/FR5ukU5y

Is there something I can change to fix this?

**Comment by Ichbinjoe** [comment]
This is a 1.13 change.

Change your plugin messaging channel to something like `nuvotifier:votes`.
