### ISSUE TITLE
Channel must be entirely lowercase | 1.13.1

### ISSUE THREAD

**Issue by AmazedMender16** [parallelblock/NuVotifier#97]
Hello,

When starting our 1.13.1 server we receive this error message.
[pastebin](https://pastebin.com/iAknTqsB)
[hastebin](https://hastebin.com/uwexikajup.css)

Regards,
Glenn R.

**Comment by Ichbinjoe** [comment]
fucking spigot.

This is fixed using the configuration. Use a lower case channel name in the configuration.

**Comment by AmazedMender16** [comment]
Already went to lower case, just created a issue so you're aware 👍
